export const employees = [
    {
        id: "1",
        name: "Sathish",
        role: "Logistics",
        phone: "+91 98765 43210",
        gender: "Male",
        experience: 7,
        avatarUrl: "/avatars/01.png",
        birthday: "1988-05-15",
        employed: true,
        hourlyPayRate: 50,
        trackAttendance: true,
        ptoDays: 10,
    },
    {
        id: "2",
        name: "Raghavendra",
        role: "TSE",
        phone: "+91 98765 43211",
        gender: "Male",
        experience: 3,
        avatarUrl: "/avatars/02.png",
        birthday: "1992-11-22",
        employed: true,
        hourlyPayRate: 50,
        trackAttendance: true,
        ptoDays: 10,
    },
    {
        id: "3",
        name: "Safee",
        role: "TSE",
        phone: "+91 98765 43212",
        gender: "Male",
        experience: 5,
        avatarUrl: "/avatars/03.png",
        birthday: "1990-03-10",
        employed: false,
        hourlyPayRate: 50,
        trackAttendance: true,
        ptoDays: 10,
    },
    {
        id: "4",
        name: "Dhiren",
        role: "MIS",
        phone: "+91 98765 43213",
        gender: "Male",
        experience: 8,
        avatarUrl: "/avatars/04.png",
        birthday: "1985-08-01",
        employed: true,
        hourlyPayRate: 73,
        trackAttendance: true,
        ptoDays: 10,
    },
    {
        id: "5",
        name: "Arjun",
        role: "Logistics",
        phone: "+91 98765 43214",
        gender: "Male",
        experience: 4,
        avatarUrl: "/avatars/05.png",
        birthday: "1991-09-05",
        employed: true,
        hourlyPayRate: 50,
        trackAttendance: true,
        ptoDays: 10,
    },
    {
        id: "6",
        name: "Aman",
        role: "Logistics",
        phone: "+91 98765 43215",
        gender: "Male",
        experience: 6,
        avatarUrl: "/avatars/06.png",
        birthday: "1987-01-20",
        employed: false,
        hourlyPayRate: 50,
        trackAttendance: true,
        ptoDays: 10,
    },
    {
        id: "8",
        name: "Neetha Jain",
        role: "Founder & CEO",
        phone: "+91 99999 99999",
        gender: "Female",
        experience: 15,
        avatarUrl: "/avatars/1xai.png",
        birthday: "2000-07-31",
        employed: true,
        trackAttendance: false,
        ptoDays: 10,
    },
    {
        id: "9",
        name: "Vijay Jain",
        role: "GM",
        phone: "+91 99999 99999",
        gender: "Male",
        experience: 15,
        avatarUrl: "/avatars/1xai.png",
        birthday: "2000-09-01",
        employed: true,
        trackAttendance: false,
        ptoDays: 10,
    },
];
export function updateEmployeeDetails(updatedEmployee) {
    const index = employees.findIndex((emp) => emp.id === updatedEmployee.id);
    if (index !== -1) {
        employees[index] = updatedEmployee;
    }
}
